name: Generate Changelog on Release

on:
  workflow_dispatch:
#  release:
#    types: [created]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Changelog
        run: docker run --rm -v "${{ github.workspace }}:/usr/local/src/your-app" githubchangeloggenerator/github-changelog-generator --user ${{ github.actor }} --project ${{ github.event.repository.name }} --token ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git add CHANGELOG.md
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git commit -m "Automatically update changelog" -a || exit 0
          git push