name: Generate Changelog

# This workflow runs after merges into the main branch
on:
  push:
    branches:
      - main

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configuration: "changelog-configuration.json"

      - name: Commit and push changes
        run: |
          git add CHANGELOG.md
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git commit -m "Automatically update changelog" -a || exit 0
          git push